const UI_CORE_COLORS = {
  transparent: "transparent",
  white: "#FFFFFF",
  black: "#000000",

  primary: {
    90: "rgb(var(--color-primary-90) / <alpha-value>)",
    80: "rgb(var(--color-primary-80) / <alpha-value>)",
    70: "rgb(var(--color-primary-70) / <alpha-value>)",
    60: "rgb(var(--color-primary-60) / <alpha-value>)",
    50: "rgb(var(--color-primary-50) / <alpha-value>)",
    40: "rgb(var(--color-primary-40) / <alpha-value>)",
    10: "rgb(var(--color-primary-10) / <alpha-value>)",
    DEFAULT: "rgb(var(--color-primary) / <alpha-value>)",
  },
  "on-primary": "rgb(var(--color-on-primary) / <alpha-value>)",
  "primary-container": "rgb(var(--color-primary-container) / <alpha-value>)",

  secondary: {
    90: "rgb(var(--color-secondary-90) / <alpha-value>)",
    80: "rgb(var(--color-secondary-80) / <alpha-value>)",
    70: "rgb(var(--color-secondary-70) / <alpha-value>)",
    60: "rgb(var(--color-secondary-60) / <alpha-value>)",
    50: "rgb(var(--color-secondary-50) / <alpha-value>)",
    40: "rgb(var(--color-secondary-40) / <alpha-value>)",
    30: "rgb(var(--color-secondary-30) / <alpha-value>)",
    20: "rgb(var(--color-secondary-20) / <alpha-value>)",
    10: "rgb(var(--color-secondary-10) / <alpha-value>)",
    5:  "rgb(var(--color-secondary-5) / <alpha-value>)",
    0:  "rgb(var(--color-secondary-0) / <alpha-value>)",
    DEFAULT: "rgb(var(--color-secondary) / <alpha-value>)",
  },
  "on-secondary": "rgb(var(--color-on-secondary) / <alpha-value>)",
  "secondary-variant": "rgb(var(--color-secondary-variant) / <alpha-value>)",
  "on-secondary-variant": "rgb(var(--color-on-secondary-variant) / <alpha-value>)",
  "secondary-container": "rgb(var(--color-secondary-container) / <alpha-value>)",
  "on-secondary-container": "rgb(var(--color-on-secondary-container) / <alpha-value>)",
  "secondary-container-variant": "rgb(var(--color-secondary-container-variant) / <alpha-value>)",

  background: {
    1: "rgb(var(--color-background-1) / <alpha-value>)",
    2: "rgb(var(--color-background-2) / <alpha-value>)",
    3: "rgb(var(--color-background-3) / <alpha-value>)",
  },

  tertiary: {
    90: "rgb(var(--color-tertiary-90) / <alpha-value>)",
    80: "rgb(var(--color-tertiary-80) / <alpha-value>)",
    70: "rgb(var(--color-tertiary-70) / <alpha-value>)",
    60: "rgb(var(--color-tertiary-60) / <alpha-value>)",
    50: "rgb(var(--color-tertiary-50) / <alpha-value>)",
    40: "rgb(var(--color-tertiary-40) / <alpha-value>)",
    30: "rgb(var(--color-tertiary-30) / <alpha-value>)",
    20: "rgb(var(--color-tertiary-20) / <alpha-value>)",
    10: "rgb(var(--color-tertiary-10) / <alpha-value>)",
    5:  "rgb(var(--color-tertiary-5) / <alpha-value>)",
    0:  "rgb(var(--color-tertiary-0) / <alpha-value>)",
    DEFAULT: "rgb(var(--color-tertiary) / <alpha-value>)",
  },
  "on-tertiary": "rgb(var(--color-on-tertiary) / <alpha-value>)",
  "tertiary-container": "rgb(var(--color-tertiary-container) / <alpha-value>)",
  "on-tertiary-container": "rgb(var(--color-on-tertiary-container) / <alpha-value>)",

  error: {
    90: "rgb(var(--color-error-90) / <alpha-value>)",
    80: "rgb(var(--color-error-80) / <alpha-value>)",
    70: "rgb(var(--color-error-70) / <alpha-value>)",
    60: "rgb(var(--color-error-60) / <alpha-value>)",
    50: "rgb(var(--color-error-50) / <alpha-value>)",
    40: "rgb(var(--color-error-40) / <alpha-value>)",
    30: "rgb(var(--color-error-30) / <alpha-value>)",
    20: "rgb(var(--color-error-20) / <alpha-value>)",
    10: "rgb(var(--color-error-10) / <alpha-value>)",
    5:  "rgb(var(--color-error-5) / <alpha-value>)",
    0:  "rgb(var(--color-error-0) / <alpha-value>)",
    DEFAULT: "rgb(var(--color-error) / <alpha-value>)",
  },
  "on-error": "rgb(var(--color-on-error) / <alpha-value>)",
  "error-container": "rgb(var(--color-error-container) / <alpha-value>)",
  "on-error-container": "rgb(var(--color-on-error-container) / <alpha-value>)",

  success: {
    90: "rgb(var(--color-success-90) / <alpha-value>)",
    80: "rgb(var(--color-success-80) / <alpha-value>)",
    70: "rgb(var(--color-success-70) / <alpha-value>)",
    60: "rgb(var(--color-success-60) / <alpha-value>)",
    50: "rgb(var(--color-success-50) / <alpha-value>)",
    40: "rgb(var(--color-success-40) / <alpha-value>)",
    30: "rgb(var(--color-success-30) / <alpha-value>)",
    20: "rgb(var(--color-success-20) / <alpha-value>)",
    10: "rgb(var(--color-success-10) / <alpha-value>)",
    5:  "rgb(var(--color-success-5) / <alpha-value>)",
    0:  "rgb(var(--color-success-0) / <alpha-value>)",
    DEFAULT: "rgb(var(--color-success) / <alpha-value>)",
  },
  "success-variant": "rgb(var(--color-success-variant) / <alpha-value>)",
  "on-success": "rgb(var(--color-on-success) / <alpha-value>)",
  "success-container": "rgb(var(--color-success-container) / <alpha-value>)",
  "on-success-container": "rgb(var(--color-on-success-container) / <alpha-value>)",

  warning: {
    90: "rgb(var(--color-warning-90) / <alpha-value>)",
    80: "rgb(var(--color-warning-80) / <alpha-value>)",
    70: "rgb(var(--color-warning-70) / <alpha-value>)",
    60: "rgb(var(--color-warning-60) / <alpha-value>)",
    50: "rgb(var(--color-warning-50) / <alpha-value>)",
    40: "rgb(var(--color-warning-40) / <alpha-value>)",
    30: "rgb(var(--color-warning-30) / <alpha-value>)",
    20: "rgb(var(--color-warning-20) / <alpha-value>)",
    10: "rgb(var(--color-warning-10) / <alpha-value>)",
    5:  "rgb(var(--color-warning-5) / <alpha-value>)",
    0:  "rgb(var(--color-warning-0) / <alpha-value>)",
    DEFAULT: "rgb(var(--color-warning) / <alpha-value>)",
  },
  "on-warning": "rgb(var(--color-on-warning) / <alpha-value>)",
  "warning-variant": "rgb(var(--color-warning-variant) / <alpha-value>)",
  "warning-container": "rgb(var(--color-warning-container) / <alpha-value>)",
  "on-warning-container": "rgb(var(--color-on-warning-container) / <alpha-value>)",

  surface: {
    1: "rgb(var(--color-surface-1) / <alpha-value>)",
    2: "rgb(var(--color-surface-2) / <alpha-value>)",
    3: "rgb(var(--color-surface-3) / <alpha-value>)",
    4: "rgb(var(--color-surface-4) / <alpha-value>)",
  },
  outline: {
    1: "rgb(var(--color-outline-1) / <alpha-value>)",
    2: "rgb(var(--color-outline-2) / <alpha-value>)",
  },
  divider: {
    1: "rgb(var(--color-divider-1) / <alpha-value>)",
    2: "rgb(var(--color-divider-2) / <alpha-value>)",
  },

  // accent palettes
  lime: {
    90: "rgb(var(--color-lime-90) / <alpha-value>)",
    80: "rgb(var(--color-lime-80) / <alpha-value>)",
    70: "rgb(var(--color-lime-70) / <alpha-value>)",
    60: "rgb(var(--color-lime-60) / <alpha-value>)",
    50: "rgb(var(--color-lime-50) / <alpha-value>)",
    40: "rgb(var(--color-lime-40) / <alpha-value>)",
    10: "rgb(var(--color-lime-10) / <alpha-value>)",
    0:  "rgb(var(--color-lime) / <alpha-value>)",
    DEFAULT: "rgb(var(--color-lime) / <alpha-value>)",
  },
  "on-lime": "rgb(var(--color-on-lime) / <alpha-value>)",
  "lime-container": "rgb(var(--color-lime-container) / <alpha-value>)",

  mint: {
    90: "rgb(var(--color-mint-90) / <alpha-value>)",
    80: "rgb(var(--color-mint-80) / <alpha-value>)",
    70: "rgb(var(--color-mint-70) / <alpha-value>)",
    60: "rgb(var(--color-mint-60) / <alpha-value>)",
    50: "rgb(var(--color-mint-50) / <alpha-value>)",
    40: "rgb(var(--color-mint-40) / <alpha-value>)",
    10: "rgb(var(--color-mint-10) / <alpha-value>)",
    DEFAULT: "rgb(var(--color-mint) / <alpha-value>)",
  },
  "on-mint": "rgb(var(--color-on-mint) / <alpha-value>)",
  "mint-container": "rgb(var(--color-mint-container) / <alpha-value>)",

  cyan: {
    90: "rgb(var(--color-cyan-90) / <alpha-value>)",
    80: "rgb(var(--color-cyan-80) / <alpha-value>)",
    70: "rgb(var(--color-cyan-70) / <alpha-value>)",
    60: "rgb(var(--color-cyan-60) / <alpha-value>)",
    50: "rgb(var(--color-cyan-50) / <alpha-value>)",
    40: "rgb(var(--color-cyan-40) / <alpha-value>)",
    10: "rgb(var(--color-cyan-10) / <alpha-value>)",
    DEFAULT: "rgb(var(--color-cyan) / <alpha-value>)",
  },
  "on-cyan": "rgb(var(--color-on-cyan) / <alpha-value>)",
  "cyan-container": "rgb(var(--color-cyan-container) / <alpha-value>)",

  blue: {
    90: "rgb(var(--color-blue-90) / <alpha-value>)",
    80: "rgb(var(--color-blue-80) / <alpha-value>)",
    70: "rgb(var(--color-blue-70) / <alpha-value>)",
    60: "rgb(var(--color-blue-60) / <alpha-value>)",
    50: "rgb(var(--color-blue-50) / <alpha-value>)",
    40: "rgb(var(--color-blue-40) / <alpha-value>)",
    10: "rgb(var(--color-blue-10) / <alpha-value>)",
    DEFAULT: "rgb(var(--color-blue) / <alpha-value>)",
  },
  "blue-variant": "rgb(var(--color-blue-variant) / <alpha-value>)",
  "on-blue": "rgb(var(--color-on-blue) / <alpha-value>)",
  "blue-container": "rgb(var(--color-blue-container) / <alpha-value>)",

  indigo: {
    90: "rgb(var(--color-indigo-90) / <alpha-value>)",
    80: "rgb(var(--color-indigo-80) / <alpha-value>)",
    70: "rgb(var(--color-indigo-70) / <alpha-value>)",
    60: "rgb(var(--color-indigo-60) / <alpha-value>)",
    50: "rgb(var(--color-indigo-50) / <alpha-value>)",
    40: "rgb(var(--color-indigo-40) / <alpha-value>)",
    10: "rgb(var(--color-indigo-10) / <alpha-value>)",
    DEFAULT: "rgb(var(--color-indigo) / <alpha-value>)",
  },
  "on-indigo": "rgb(var(--color-on-indigo) / <alpha-value>)",
  "indigo-container": "rgb(var(--color-indigo-container) / <alpha-value>)",

  purple: {
    90: "rgb(var(--color-purple-90) / <alpha-value>)",
    80: "rgb(var(--color-purple-80) / <alpha-value>)",
    70: "rgb(var(--color-purple-70) / <alpha-value>)",
    60: "rgb(var(--color-purple-60) / <alpha-value>)",
    50: "rgb(var(--color-purple-50) / <alpha-value>)",
    40: "rgb(var(--color-purple-40) / <alpha-value>)",
    10: "rgb(var(--color-purple-10) / <alpha-value>)",
    DEFAULT: "rgb(var(--color-purple) / <alpha-value>)",
  },
  "on-purple": "rgb(var(--color-on-purple) / <alpha-value>)",
  "purple-container": "rgb(var(--color-purple-container) / <alpha-value>)",

  pink: {
    90: "rgb(var(--color-pink-90) / <alpha-value>)",
    80: "rgb(var(--color-pink-80) / <alpha-value>)",
    70: "rgb(var(--color-pink-70) / <alpha-value>)",
    60: "rgb(var(--color-pink-60) / <alpha-value>)",
    50: "rgb(var(--color-pink-50) / <alpha-value>)",
    40: "rgb(var(--color-pink-40) / <alpha-value>)",
    10: "rgb(var(--color-pink-10) / <alpha-value>)",
    DEFAULT: "rgb(var(--color-pink) / <alpha-value>)",
  },
  "on-pink": "rgb(var(--color-on-pink) / <alpha-value>)",
  "pink-container": "rgb(var(--color-pink-container) / <alpha-value>)",

  rose: {
    90: "rgb(var(--color-rose-90) / <alpha-value>)",
    80: "rgb(var(--color-rose-80) / <alpha-value>)",
    70: "rgb(var(--color-rose-70) / <alpha-value>)",
    60: "rgb(var(--color-rose-60) / <alpha-value>)",
    50: "rgb(var(--color-rose-50) / <alpha-value>)",
    40: "rgb(var(--color-rose-40) / <alpha-value>)",
    10: "rgb(var(--color-rose-10) / <alpha-value>)",
    DEFAULT: "rgb(var(--color-rose) / <alpha-value>)",
  },
  "on-rose": "rgb(var(--color-on-rose) / <alpha-value>)",
  "rose-container": "rgb(var(--color-rose-container) / <alpha-value>)",

  yellow: {
    90: "rgb(var(--color-yellow-90) / <alpha-value>)",
    80: "rgb(var(--color-yellow-80) / <alpha-value>)",
    70: "rgb(var(--color-yellow-70) / <alpha-value>)",
    60: "rgb(var(--color-yellow-60) / <alpha-value>)",
    50: "rgb(var(--color-yellow-50) / <alpha-value>)",
    40: "rgb(var(--color-yellow-40) / <alpha-value>)",
    10: "rgb(var(--color-yellow-10) / <alpha-value>)",
    DEFAULT: "rgb(var(--color-yellow) / <alpha-value>)",
  },
  "on-yellow": "rgb(var(--color-on-yellow) / <alpha-value>)",
  "yellow-container": "rgb(var(--color-yellow-container) / <alpha-value>)",
};

module.exports = { UI_CORE_COLORS };

